import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faUser,
	faHouse,
	faNewspaper,
	faCompass,
	faBell,
	faEnvelope,
	faCircleUser,
	faFloppyDisk,
	faPaperPlane,
	faTrashCan,
} from "@fortawesome/free-regular-svg-icons";
import {
	faXmark,
	faChevronDown,
	faMagnifyingGlass,
	faPencil,
	faChevronUp,
	faArrowRightToBracket,
	faLock,
	faEye,
	faEyeSlash,
	faRightFromBracket,
	faPlus,
	faArrowLeft,
} from "@fortawesome/free-solid-svg-icons";

library.add(
	faArrowLeft,
	faPlus,
	faTrashCan,
	faXmark,
	faChevronDown,
	faPaperPlane,
	faFloppyDisk,
	faUser,
	faHouse,
	faNewspaper,
	faCompass,
	faMagnifyingGlass,
	faPencil,
	faBell,
	faChevronDown,
	faChevronUp,
	faArrowRightToBracket,
	faEnvelope,
	faLock,
	faEye,
	faEyeSlash,
	faCircleUser,
	faRightFromBracket,
);
